package driver

import (
	"context"
	"errors"
	"strings"
	"time"
)

/*
This JobRecord is the driver-level representation of a Job.
This is the struct that will be saved in some backend (Redis/SQL/etc...)

NOTES:
------
  - Payload is bytes only.
  - Should not import taskharbor to avoid circular deps.
*/
type JobRecord struct {
	ID             string        // Unique identifier generated by Client
	Type           string        // Used to pick the handler
	Payload        []byte        // Encoded payload bytes
	Queue          string        // Queue name
	RunAt          time.Time     // Scheduled time (0 means runnable now)
	Timeout        time.Duration // Max allowed time for Job
	IdempotencyKey string        // Allow idempotency during multiple calls (MILESTONE 6)
	CreatedAt      time.Time     // Time when Job was created
	Attempts       int           // Max retry amounts
}

/*
This function validates the JobRecord before a driver stores it.
Drivers can call this to keep behavior consistent.
*/
func (r JobRecord) Validate() error {
	if strings.TrimSpace(r.ID) == "" {
		return ErrJobIDRequired
	}
	if strings.TrimSpace(r.Type) == "" {
		return ErrJobTypeRequired
	}
	if strings.TrimSpace(r.Queue) == "" {
		return ErrQueueRequired
	}
	if r.Timeout < 0 {
		return ErrNegativeTimeout
	}
	return nil
}

/*
Driver is the backend contract.

Milestone 2 contract:
- Enqueue stores a job (runnable or scheduled via RunAt)
- Reserve returns one runnable job (RunAt <= now)
- Ack marks the reserved job completed
- Fail marks the reserved job failed and stores it into DLQ (driver-owned)
- Reserve is non-blocking in v0 (ok=false means nothing runnable)

No leases in milestone 2.
No retries in milestone 2.
*/
type Driver interface {
	Enqueue(ctx context.Context, rec JobRecord) error
	Reserve(ctx context.Context, queue string, now time.Time) (JobRecord, bool, error)
	Ack(ctx context.Context, id string) error
	Fail(ctx context.Context, id string, reason string) error
	Close() error
}

// Errors
var (
	ErrJobIDRequired   = errors.New("job id is required")
	ErrJobTypeRequired = errors.New("job type is required")
	ErrQueueRequired   = errors.New("queue is required")
	ErrNegativeTimeout = errors.New("timeout cannot be negative")
	ErrJobNotFound     = errors.New("job not found")
	ErrJobNotInflight  = errors.New("job is not inflight")
)
